// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMrTw70m6ct5k5v6K-MMugqyUlJglrgoI',
    appId: '1:491908629457:web:327bb3efe25f344c4b16f0',
    messagingSenderId: '491908629457',
    projectId: 'app-login-3365b',
    authDomain: 'app-login-3365b.firebaseapp.com',
    storageBucket: 'app-login-3365b.firebasestorage.app',
    measurementId: 'G-1W9D3L0ZC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfowpGRib4QqAVGc4GRuoUY75anKv5tlQ',
    appId: '1:491908629457:android:531abd79cb55bf8d4b16f0',
    messagingSenderId: '491908629457',
    projectId: 'app-login-3365b',
    storageBucket: 'app-login-3365b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-B3D1vPpiS-xgQC6Mfm1FehmTqz9vVB0',
    appId: '1:491908629457:ios:5f849fc03d6a537d4b16f0',
    messagingSenderId: '491908629457',
    projectId: 'app-login-3365b',
    storageBucket: 'app-login-3365b.firebasestorage.app',
    iosBundleId: 'com.example.appProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-B3D1vPpiS-xgQC6Mfm1FehmTqz9vVB0',
    appId: '1:491908629457:ios:5f849fc03d6a537d4b16f0',
    messagingSenderId: '491908629457',
    projectId: 'app-login-3365b',
    storageBucket: 'app-login-3365b.firebasestorage.app',
    iosBundleId: 'com.example.appProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMrTw70m6ct5k5v6K-MMugqyUlJglrgoI',
    appId: '1:491908629457:web:802c47d9330bc5094b16f0',
    messagingSenderId: '491908629457',
    projectId: 'app-login-3365b',
    authDomain: 'app-login-3365b.firebaseapp.com',
    storageBucket: 'app-login-3365b.firebasestorage.app',
    measurementId: 'G-P4E382VD4C',
  );
}
